version: '3'
services:
  backend:
    build: ./backXpert
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/mydatabase
      - JWT_SECRET=3F6b446auRD8HZyxgPTa1TElEfMZpf7rLxr7pYV8vX0FbgeSmzU8WDDVhpbCooRH
      - API_BASE_URL=https://api.thecatapi.com/v1
    volumes:
      - ./backXpert:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontXpert
    ports:
      - '80:80'
    volumes:
      - ./frontXpert:/usr/src/app
    depends_on:
      - backend

  db:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
